@startuml
skinparam class {
    BackgroundColor<<Domain>> Wheat
    BorderColor<<Domain>> Tomato
}

interface Command {
    + execute(system: Any)
}

together {
    class Bank <<Domain>> {
    }
    class Account <<Domain>> {
        + id: String
        + name: String
        + balance: Amount
    }
    Bank "1" *--> "0..*" Account
}

    interface BankCommand {
        + execute(bank: Bank)
    }
    Command <|.. BankCommand
    BankCommand ..> Bank: modifies >

class CreateAccount {
    + id: String
    + name: String
}
BankCommand <|-- CreateAccount
CreateAccount ..> Account: creates >

together {

    together {
    class Deposit extends BankCommand {
        + accountId: String
        + amount: Amount
    }

    class Withdrawal extends BankCommand {
        + accountId: String
        + amount: Amount
    }

    class Transfer extends BankCommand {
        + accountId: String
        + amount: Amount
    }
    Transfer ..> Deposit: uses >
    Transfer ..> Withdrawal: uses >
    }
}

@enduml